import type { Metadata } from "next";
import { SiteHeader } from "@/components/SiteHeader";
import { Footer } from "@/components/Footer";
import { ButtonLink } from "@/components/ButtonLink";
import { ShieldCheck, Lock, EyeOff, HeartHandshake } from "lucide-react";

export const metadata: Metadata = {
  title: "About PageCub — How It Works & Our Safety Approach",
  description: "How PageCub creates personalized illustrated children's storybooks, and how we handle your child's information.",
};

export default function AboutPage() {
  return (
    <>
      <SiteHeader />
      <main>
        <section className="page-shell py-24">
          <div className="max-w-2xl">
            <p className="text-sm font-bold uppercase tracking-widest text-sage mb-4">About PageCub</p>
            <h1 className="display text-5xl font-bold leading-tight mb-6">Built for one child. Built for yours.</h1>
            <p className="text-lg leading-8 text-ink/72">
              PageCub is a personalized illustrated storybook service. You tell us about your child — who they are, what they love, what they&apos;re going through — and we create a complete chapter book built around them, with real illustrations, a beginning, a heart, and an ending that fits.
            </p>
          </div>
        </section>

        <section className="border-y border-line bg-card/70 py-16">
          <div className="page-shell max-w-2xl">
            <h2 className="display text-3xl font-bold mb-6">About Aurelia</h2>
            <p className="text-lg leading-9 text-ink/75">
              You&apos;ll notice most of our examples follow the same little girl, Aurelia. That&apos;s my daughter. I originally built PageCub because I wanted to make her books — stories built around whatever she was going through, whatever she was into, whatever she couldn&apos;t find on the shelf. She was the first reader. She still is.
            </p>
          </div>
        </section>

        <section className="page-shell py-16 max-w-2xl">
          <h2 className="display text-3xl font-bold mb-4">How the books are made</h2>
          <p className="text-ink/70 leading-7 mb-6">
            When you submit the creation form, our system uses the details you provide — your child&apos;s name, appearance, personality, world preferences, and the lesson you want the story to carry — to generate a complete 10-chapter illustrated storybook.
          </p>
          <p className="text-ink/70 leading-7 mb-6">
            The story and illustrations are generated by automated creative tools trained on children&apos;s literature and illustration styles. No human author or illustrator reviews your specific book before delivery. What you receive is a finished, cohesive narrative with two full text pages and two illustrations per chapter — ready to read, save, or share.
          </p>
          <p className="text-ink/70 leading-7 mb-6">
            Every book includes a dedication page, opening note, and back matter with discussion questions and a draw-along prompt — all generated to match the tone and theme of your specific story.
          </p>
          <p className="text-ink/70 leading-7">
            You can choose from any illustration style in the creation form — watercolor, classic storybook, whimsical fantasy, cartoon, and more. The style you select shapes every illustration in the book consistently.
          </p>
        </section>

        <section className="bg-sage/10 py-16">
          <div className="page-shell max-w-2xl">
            <h2 className="display text-3xl font-bold mb-4">What you get</h2>
            <div className="rounded-2xl border border-line bg-card p-6 space-y-3 text-sm text-ink/75 leading-7">
              {[
                "10-chapter personalized storybook",
                "2 text pages + 2 illustrations per chapter (20 illustrations total)",
                "Title page and cover",
                "Dedication page",
                "Opening note page",
                "Back matter: what the hero learned, follow-up questions for conversation, draw-along prompt",
                "Delivered as a high-quality PDF",
                "Print fulfillment coming soon — hardcover, ~48 pages",
              ].map((item) => (
                <div key={item} className="flex items-start gap-3">
                  <span className="mt-1 h-2 w-2 rounded-full bg-honey flex-shrink-0" />
                  <span>{item}</span>
                </div>
              ))}
            </div>
          </div>
        </section>

        <section className="page-shell py-16 max-w-2xl">
          <h2 className="display text-3xl font-bold mb-8">How we handle your information</h2>
          <div className="grid gap-5 sm:grid-cols-2">
            {[
              { Icon: Lock, title: "Private by design", body: "Details you submit about your child are used only to create your book. They are not shared with advertisers, sold to data brokers, or used to build profiles." },
              { Icon: EyeOff, title: "No data selling", body: "We do not sell, rent, or trade your personal information or your child's information to any third party. Full stop." },
              { Icon: ShieldCheck, title: "Made with permission", body: "The creation form requires confirmation that you are the parent, guardian, or have explicit permission to create a book for the child described." },
              { Icon: HeartHandshake, title: "You can request deletion", body: "If you want your data and your child's details removed from our systems, email support@pagecub.com and we will honor that request." },
            ].map(({ Icon, title, body }) => (
              <div key={title} className="rounded-2xl border border-line bg-card p-6">
                <Icon className="h-6 w-6 text-sage mb-4" />
                <h3 className="font-bold mb-2">{title}</h3>
                <p className="text-sm text-ink/65 leading-6">{body}</p>
              </div>
            ))}
          </div>
        </section>

        <section className="page-shell pb-16 max-w-2xl">
          <h2 className="display text-3xl font-bold mb-4">Questions?</h2>
          <p className="text-ink/70 leading-7 mb-6">
            Reach us at <a href="mailto:support@pagecub.com" className="text-honey font-bold hover:underline">support@pagecub.com</a>. We&apos;re happy to answer questions about how the books are made, what data we hold, or anything else before you create.
          </p>
          <ButtonLink href="/create">Start a Book</ButtonLink>
        </section>
      </main>
      <Footer />
    </>
  );
}
